name: Release

on:
  push:
    tags:
      - "*.*"
      - "*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  label-detector:
    name: Runner Label
    runs-on: label-detector
    outputs:
      runs-on: ${{ steps.detector.outputs.label }}
    steps:
      - name: Detect Label
        id: detector
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: label-detector
    runs-on: "${{ needs.label-detector.outputs.runs-on }}"
    steps:
      - uses: actions/checkout@v1


      - name: Print version info
        id: semver
        run: |
          cd rabbitmq-init
          make version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run checks
        run: |
          make promu
          make check_license style staticcheck unused build test-short
          make ci

      - name: Build
        env:
          DOCKER_REPO: kubedb
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          export DOCKER_IMAGE_TAG=${GITHUB_REF#"refs/tags/"}
          docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
          promu crossbuild
          make docker
          make docker-publish
          make docker-manifest
          make release